backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "episodes"
    label: "Odcinki"
    folder: "episodes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Numer odcinka", name: "number", widget: "number" }
      - { label: "Opis", name: "description", widget: "text" }
      - { label: "Link do odcinka", name: "link", widget: "string" }